# Generated by Django 4.1.7 on 2023-03-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_author_item_added_user_item_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
